### ISSUE TITLE
Chinese IME is still not working

### ISSUE THREAD

**Issue by dvorak0** [puritys/chromeSecureShell#5]
**Describe the bug**
Chinese IME is still not working after I enable 'enable-input-method'.

I am using Chrome 80.0 on Windows 10 64bit.

![a](https://user-images.githubusercontent.com/2220369/75221186-2dbcf000-57dc-11ea-9fbb-a4f4698031b8.gif)

Thanks.

**Comment by puritys** [comment]
Chrome SSH Client already support Chinese typing and ssh-agent, you have to install the version bigger than 0.8.42.1. 

- ssh-agent: https://github.com/google/chrome-ssh-agent


This repo won't upgrade anymore.  If you really want to use this hack extension. please install the extension on  chromium Version 68.0.3403.0.

Windows chromium: https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/552589/
Mac chromium: https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac/552589/

**Comment by dvorak0** [comment]
Thanks!
